#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive

installpkg(){
    dpkg-query --status $1 >/dev/null || apt-get install -y $1
}

apt-get install python-software-properties
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install -y php7.1

apt-get install php7.1-mysql

apt-get update

installpkg redis-server
installpkg mysql-server
installpkg apache2-utils
installpkg apache2-suexec-custom

echo "ServerName localhost" > /etc/apache2/conf-enabled/servername.conf
a2enmod suexec
a2dissite 000-default.conf
cp /tmp/001-talented.conf /etc/apache2/sites-available
a2ensite  001-talented.conf
service apache2 restart

bootstrapdb(){
    cat <<EOF | mysql -uroot
    DROP DATABASE IF EXISTS samtt;
    CREATE DATABASE samtt;
    USE samtt;
    CREATE TABLE mo (
      id int NOT NULL auto_increment,
      msisdn varchar(20),
      operatorid int,
      shortcodeid int,
      text varchar(255),
      auth_token varchar(60),
      created_at DATETIME,
      PRIMARY KEY(id)
    ) ;
EOF
}

create_index(){
    cat <<EOF | mysql -uroot
    USE samtt;
    CREATE INDEX  created_at_inde on mo (created_at) using BTREE;
EOF
}

echo "creating database";
bootstrapdb

echo "create index created_at"
create_index

populate_db() {
    /tmp/populate_db 10000000| mysql -u root samtt
}

echo "seeding databsae";
populate_db
