#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive

bootstrapdb(){
    cat <<EOF | mysql -uroot -proot
    DROP DATABASE IF EXISTS samtt;
    CREATE DATABASE samtt;
    USE samtt;
    CREATE TABLE mo (
      id int NOT NULL auto_increment,
      msisdn varchar(20),
      operatorid int,
      shortcodeid int,
      text varchar(255),
      auth_token varchar(60),
      created_at DATETIME,
      PRIMARY KEY(id)
    ) ;
EOF
}

create_index(){
    cat <<EOF | mysql -uroot -proot
    USE samtt;
    CREATE INDEX  created_at_inde on mo (created_at) using BTREE;
EOF
}

echo "creating database";
bootstrapdb

echo "create index created_at"
create_index

populate_db() {
    populate_db 10000000| mysql -u root -p root samtt
}

echo "seeding databsae";
populate_db
